### ISSUE TITLE
[Question] Caching of surveys onto the device

### ISSUE THREAD

**Issue by suho** [SchwartzLizer/NimbleSurvey#4]
## Issue

While you have implemented caching of surveys, you did not use that data to show on the UI.

https://github.com/SchwartzLizer/NimbleSurvey/blob/ddfb80dcf8bc3a802aa6cc46158444bf75e38101/NimbleSurvey/NimbleSurvey/Scene/Home/HomeViewModel.swift#L149-L159

The feature is not implemented properly. How can we improve this?

**Comment by SchwartzLizer** [comment]
@suho To be honest, I don't understand the optional feature task "Implement the caching of surveys onto the device."
because I think the survey app should get new lists from the server every time the app runs. Until you open this issue, it will help me understand what I need to do.

So, we can improve by
1. When the user runs into the home screen, the application will call the API service.
2. If the service response is 200, we will save it to the local device.
3. Next time, when the user runs into the home screen and calls the API service If not 200, we will get the local data from the device to show the user.
4. If the local data from the device is not found, we will give an error to the user.

**Comment by SchwartzLizer** [comment]
@suho I prepared the function already, but I can't login with the developed username and password

**Comment by suho** [comment]
@SchwartzLizer That's a good approach, let's implement that
